services:
  - name: client
    type: static
    buildCommand: |
      cd client
      npm install
      npm run build
    publishDir: client/dist
    envVars:
      - key: NODE_ENV
        value: production

  - name: server
    type: web
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
