# render.yaml

services:
  - name: client
   type: static
    buildCommand: npm run build
    publishDir: frontend/dist
    envVars:
      - key: NODE_ENV
        value: production

  - name: server
    type: web
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
